version: "3.8"

services:
  # Strategy Engine
  strategy_engine:
    image: strategy-engine:latest
    build: ../../services/strategy_engine
    container_name: strategy_engine
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
    restart: always
    networks:
      - strategy_net

networks:
  strategy_net:
    driver: bridge
